/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;
import clases.Producto;
import clases.ProductoEstudiantil;
import java.awt.Image;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author ESTUDIANTE
 */
public class Agregar extends javax.swing.JDialog {

    /**
     * Creates new form Agregar
     */
    public Agregar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();      
        
        ruta = "src/datos/productos.txt";
        try {
            productos = Helper.traerDatos(ruta);
            salida = new ObjectOutputStream(new FileOutputStream(ruta));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        Helper.volcado(salida, productos);
        JButton botonesH[] = {cmdBuscar, cmdSalir};
        JButton botonesD[] = {cmdAgregar};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);

    }
    String ruta = "src/datos/productos.txt";
    ObjectOutputStream salida;
    ArrayList<ProductoEstudiantil> productos;
    int aux = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cmdSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        cmdAgregar = new javax.swing.JButton();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblCantidad1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        cmdBuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portada.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Producto");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        cmdSalir.setBackground(new java.awt.Color(255, 51, 51));
        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        getContentPane().add(cmdSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 90, 40));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel3.setToolTipText("");
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 90, 30));

        txtMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMarcaKeyTyped(evt);
            }
        });
        jPanel3.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 90, 30));

        lblNombre.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblNombre.setText("Nombre");
        jPanel3.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 70, 20));

        lblMarca.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblMarca.setText("Marca");
        jPanel3.add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        cmdAgregar.setText("Agregar");
        cmdAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 100, 40));

        lblPrecio.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblPrecio.setText("Precio");
        jPanel3.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        jPanel3.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 90, 30));

        lblCantidad.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblCantidad.setText("Cantidades");
        jPanel3.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });
        jPanel3.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 90, 30));

        lblCantidad1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblCantidad1.setText("Numero ID");
        jPanel3.add(lblCantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        jPanel3.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 90, 30));

        cmdBuscar.setBackground(new java.awt.Color(153, 204, 255));
        cmdBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        cmdBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 50, 50));

        jButton1.setText("Borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 100, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 320, 430));

        setSize(new java.awt.Dimension(465, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAgregarActionPerformed
        String nombre, marca, codigo;
        int precio, cantidad;
        Producto p;
        if (txtNombre.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Por favor, digite un nombre", 2);
        } else if (txtMarca.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Por favor, digite una marca", 2);
        } else if (txtPrecio.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Por favor, digite un precio", 2);
        }else if (txtCantidad.getText().trim().isEmpty()){
            Helper.mensaje(this, "Por favor, digite una cantidad", 2);
        }else if (txtCodigo.getText().trim().isEmpty()){
            Helper.mensaje(this, "Por favor, digite un codigo", 3);
        }else{
        nombre = txtNombre.getText();
        marca = txtMarca.getText();
        precio = Integer.parseInt(txtPrecio.getText());
        cantidad = Integer.parseInt(txtCantidad.getText());
        codigo = txtCodigo.getText();
        ArrayList<ProductoEstudiantil> productosMod;
        try {
            if (aux == 0) {

                p = new ProductoEstudiantil(precio, marca, nombre, cantidad, codigo);

                p.escribir(salida);

            } else {
                productosMod = Helper.modificarProducto(ruta, precio, marca, nombre, cantidad, codigo);
                salida = new ObjectOutputStream(new FileOutputStream(ruta));
                Helper.volcado(salida, productosMod);
                aux = 0;
                Helper.mensaje(this, "Producto Actualizado Correctamente!", 1);
            }
        } catch (IOException ex) {
            Logger.getLogger(Agregar.class.getName()).log(Level.SEVERE, null, ex);
        }

        txtNombre.setText("");
        txtMarca.setText("");
        txtPrecio.setText("");
        txtCodigo.setText("");
        txtCantidad.setText("");
        JButton botonesH[] = {cmdBuscar, cmdSalir};
        JButton botonesD[] = {cmdAgregar};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
        }
    }//GEN-LAST:event_cmdAgregarActionPerformed

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void cmdBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarActionPerformed
        String codigo;
        if (txtCodigo.getText().trim().isEmpty()){
            Helper.mensaje(this, "Digite un codigo", 2);
        }else{
        codigo = txtCodigo.getText();
        ProductoEstudiantil p;
        if (Helper.buscarProductoCodigo(codigo, ruta)) {
            p = Helper.traerProductoCodigo(codigo, ruta);
            txtNombre.setText(p.getNombre());
            txtMarca.setText(p.getMarca());
            txtPrecio.setText("" + p.getPrecio());
            txtCantidad.setText("" + p.getCantidades());
         

            aux = 1;
        } else {
            txtNombre.requestFocusInWindow();
            aux = 0;
            JOptionPane.showMessageDialog(this, "No existe ningún producto con este código", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        }
        JButton botonesH[] = {cmdAgregar, cmdSalir};
        JButton botonesD[] = {cmdBuscar};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
        }
        
    }//GEN-LAST:event_cmdBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtNombre.setText("");
        txtMarca.setText("");
        txtPrecio.setText("");
        txtCantidad.setText("");
        txtCodigo.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
      char c=evt.getKeyChar(); 
          if(Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtMarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMarcaKeyTyped
          char c=evt.getKeyChar(); 
          if(Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtMarcaKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
          char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
       char c=evt.getKeyChar(); 
       
          if(!Character.isDigit(c)&&evt.getKeyChar()!='0') {   
            getToolkit().beep();    
              evt.consume();   
          }
            if(evt.getKeyChar()=='0'&&txtCantidad.getText().contains("0")){
        evt.consume();
    }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
          if(!Character.isDigit(c) ) { 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtCodigoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Agregar dialog = new Agregar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAgregar;
    private javax.swing.JButton cmdBuscar;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCantidad1;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
