/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author ESTUDIANTE
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        cmdComenzar.setEnabled(true);
        cmdFinalizar.setEnabled(false);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/logo.png"));
        setIconImage(icon);
        setVisible(true);
        mnOpciones.setEnabled(false);
        mnProductos.setEnabled(false);
        mnReportes.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdBorrar = new javax.swing.JButton();
        cmdFinalizar = new javax.swing.JButton();
        cmdComenzar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnOpciones = new javax.swing.JMenu();
        mnComprar = new javax.swing.JMenuItem();
        mnVer = new javax.swing.JMenuItem();
        mnProductos = new javax.swing.JMenu();
        mnAgregarProducto = new javax.swing.JMenuItem();
        mnPedir = new javax.swing.JMenuItem();
        mnReportes = new javax.swing.JMenu();
        mnMarca = new javax.swing.JMenuItem();
        mnNombre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Papelería");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdBorrar.setBackground(new java.awt.Color(255, 51, 51));
        cmdBorrar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmdBorrar.setText("Borrar todo");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 200, 50));

        cmdFinalizar.setBackground(new java.awt.Color(153, 204, 255));
        cmdFinalizar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmdFinalizar.setText("Finalizar Jornada");
        cmdFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(cmdFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 270, 60));

        cmdComenzar.setBackground(new java.awt.Color(153, 204, 255));
        cmdComenzar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmdComenzar.setText("Comenzar jornada");
        cmdComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdComenzarActionPerformed(evt);
            }
        });
        getContentPane().add(cmdComenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 270, 70));

        mnOpciones.setText("Inventario");

        mnComprar.setText("Comprar");
        mnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnComprarActionPerformed(evt);
            }
        });
        mnOpciones.add(mnComprar);

        mnVer.setText("Ver listado");
        mnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVerActionPerformed(evt);
            }
        });
        mnOpciones.add(mnVer);

        jMenuBar1.add(mnOpciones);

        mnProductos.setText("Pedir productos");

        mnAgregarProducto.setText("Agregar y buscar");
        mnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAgregarProductoActionPerformed(evt);
            }
        });
        mnProductos.add(mnAgregarProducto);

        mnPedir.setText("Agregar cantidades");
        mnPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPedirActionPerformed(evt);
            }
        });
        mnProductos.add(mnPedir);

        jMenuBar1.add(mnProductos);

        mnReportes.setText("Reportes");

        mnMarca.setText("Listar por marca");
        mnMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMarcaActionPerformed(evt);
            }
        });
        mnReportes.add(mnMarca);

        mnNombre.setText("Listado por nombre");
        mnNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNombreActionPerformed(evt);
            }
        });
        mnReportes.add(mnNombre);

        jMenuBar1.add(mnReportes);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(941, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnComprarActionPerformed
        Comprar a = new Comprar(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_mnComprarActionPerformed

    private void mnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVerActionPerformed
        Ver a = new Ver(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_mnVerActionPerformed

    private void cmdFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFinalizarActionPerformed
    Gastos a = new Gastos(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_cmdFinalizarActionPerformed

    private void cmdComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdComenzarActionPerformed
        Helper.mensaje(this, "Su jornada ha comenzado, dele click en finalizar jornada para finalizarla y conocer sus ganancias", 1);
        cmdComenzar.setEnabled(false);
        cmdFinalizar.setEnabled(true);
        mnOpciones.setEnabled(true);
        mnProductos.setEnabled(true);
        mnReportes.setEnabled(true);
    }//GEN-LAST:event_cmdComenzarActionPerformed

    private void mnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAgregarProductoActionPerformed
        Agregar a = new Agregar(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_mnAgregarProductoActionPerformed

    private void mnMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMarcaActionPerformed
        ListadoPorMarca a = new ListadoPorMarca(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_mnMarcaActionPerformed

    private void mnNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNombreActionPerformed
        ListadoPorNombre a = new ListadoPorNombre(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_mnNombreActionPerformed

    private void mnPedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPedirActionPerformed
        Pedir a = new Pedir(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_mnPedirActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdComenzar;
    private javax.swing.JButton cmdFinalizar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnAgregarProducto;
    private javax.swing.JMenuItem mnComprar;
    private javax.swing.JMenuItem mnMarca;
    private javax.swing.JMenuItem mnNombre;
    private javax.swing.JMenu mnOpciones;
    private javax.swing.JMenuItem mnPedir;
    private javax.swing.JMenu mnProductos;
    private javax.swing.JMenu mnReportes;
    private javax.swing.JMenuItem mnVer;
    // End of variables declaration//GEN-END:variables
}
